#include "Input.h"

RCaptureOnMousesWheelsDelegate MousesWheelsDelegate;
RCaptureOnMousesDelegate RMouseDownDelegate;
RCaptureOnMousesDelegate RMouseUpDelegate;
RCaptureOnMousesDelegate LMouseDownDelegate;
RCaptureOnMousesDelegate LMouseUpDelegate;
RCaptureOnMousesDelegate MouseMoveDelegate;
RCaptureOnMousesDelegate ResizeScreenDelegate;