#include "Input.h"

FCaptureOnMousesWheelsDelegate MousesWheelsDelegate;
FCaptureOnMousesDelegate RMouseDownDelegate;
FCaptureOnMousesDelegate RMouseUpDelegate;
FCaptureOnMousesDelegate LMouseDownDelegate;
FCaptureOnMousesDelegate LMouseUpDelegate;
FCaptureOnMousesDelegate MouseMoveDelegate;