#pragma once
enum class EMeshRenderLayerType
{
	RENDERLAYER_OPAQUE = 0,
	RENDERLAYER_CUBEMAP=1,
	RENDERLAYER_SELECT=2,
	RENDERLAYER_OPERATION_HANDLE_POSITION = 3,
	RENDERLAYER_OPERATION_HANDLE_ROTATE=4,
	RENDERLAYER_OPAQUE_REFLECTOR=5,
};
