#pragma once
enum class EMeshRenderLayerType
{
	RENDERLAYER_OPAQUE = 0,
	RENDERLAYER_CUBEMAP=1,
	RENDERLAYER_SELECT=2,
	RENDERLAYER_OPERATION_HANDLE = 3,
	RENDERLAYER_OPERATION_HANDLE_ROT_PLANE=4,
};
